ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS end_date DATE,
  ADD COLUMN IF NOT EXISTS total_days INTEGER,
  ADD COLUMN IF NOT EXISTS total_amount BIGINT;
